name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Pipeline with Crumb
        run: |
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')

          curl -X POST \
          -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          -H "Jenkins-Crumb: $CRUMB" \
          "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/build"
